Program Aula_02_Variaveis ;	
	Var
	NomePessoa:String;
	SenhaPessoa:String[16];
	IdadePessoa:Integer;
	AlturaPessoa:Real;
	GeneroPessoa:Char;
	PessoaVIP:Boolean;
Begin
  Writeln('Aplicativo que faz relatórios ;)');
  Writeln;
  Writeln('Primeiro Digite seu nome completo: ');
  Readln(NomePessoa);
  Writeln('Digite sua Senha: <Máx 16 Caracteres> ');
  Readln(SenhaPessoa);
  Writeln('Digite sua Idade: ');
  Readln(IdadePessoa);
  Writeln('Digite sua Altura: ');
  Readln(AlturaPessoa);
  Writeln('Digite seu genero (M ou F): ');
  Readln(GeneroPessoa);
  Writeln('Você é VIP? True ou False apenas!');
  Readln(PessoaVIP);
  clrscr;
  Writeln('Estamos fazendo seu relatório.');
  delay(2000);
  clrscr;
  Writeln('Estamos fazendo seu relatório..');
  delay(0500);
  clrscr;
  Writeln('Estamos fazendo seu relatório...');
  delay(0500);
  clrscr;
  Writeln('Estamos fazendo seu relatório....');
  delay(0500);
  clrscr;
  Writeln('Estamos fazendo seu relatório.....');
  delay(0500);
  clrscr;
  Writeln('Seu relatório está pronto! :)');
  delay(200);
  clrscr;
  Writeln('----------Relatório gerado pela Empresa GeraView-----------------');
  Writeln;
  Writeln('Seu nome completo é: ', NomePessoa);
  Writeln('Senha cadastrada: ', SenhaPessoa);
  Writeln;
  Writeln('Idade:', IdadePessoa,'. Altura: ',AlturaPessoa:0:0,'. Genêro: ',GeneroPessoa,'.');
  Writeln('Status de VIP: ',PessoaVIP,'.' );
End.